### ISSUE TITLE
Trust me bro

### ISSUE THREAD

**Issue by DmytroTeliukov** [Team-Alexander/helloworld#9]
### Description
Make new api

### Tasks

- [ ] create get list endpoint
- [ ] post new item endpoint
- [ ] delete item endpoint
